### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/docs#41]
Checklist to update existing docs

- [x] If somebody wants to install ee3, there should be a doc with clear instructions. We can also setup `rt.cx/ee3` URL.
- [x] Migration guide from ee3 > ee4
- [x] HHVM deprecation #778 
- [x] Syntax change for `--key=value` #778 
- [x] Mail stack support drop (or moved to package). #778 
- [x] Remove experimental status #779 
- [x] Update README.md in GitHub Project.
- [x] Update EasyEngine Homepage
